return {
    indent = '│',
    fold = ' ',
    common = {
        search = '',
        word = '󰈭',
        recent = '󰈙',
        bookmark = '',
        keymap = '',
        terminal = '',
        source = '',
        regex = '',
        lua = '',
        lazy = '󰒲 ',
        help = '󰋖',
        input = '󰬴',
        -- arrow = '→',
        arrow = '->',
        plugin = '',
        chevron_right = '',
        chevron_down = '',
    },
    diagnostics = {
        error = '',
        warn = '',
        info = '',
        hint = '󰌶',
    },
    gutter = {
        add = '│',
        change = '│',
        delete = '_',
        topdelete = '‾',
        changedelete = '~',
        untracked = '┆',
    },
    package = {
        installed = '●',
        pending = '○',
        uninstalled = '○',
    },
    tree = {
        default = '',
        symlink = '',
        bookmark = '󰆤',
        modified = '●',
        hidden = '󰜌',
        folder = {
            arrow_closed = '',
            arrow_open = '',
            default = '',
            open = '',
            empty = '',
            empty_open = '',
            symlink = '',
            symlink_open = '',
        },
        git = {
            unstaged = '',
            staged = '',
            unmerged = '',
            untracked = '',
            renamed = '',
            deleted = '',
            ignored = '',
        },
    },

    kinds = {
        Method = '  ',
        Function = '  ',
        Constructor = '  ',
        Field = '  ',
        Variable = '  ',
        Class = '  ',
        Interface = '  ',
        Module = '  ',
        Property = '  ',
        Unit = '  ',
        Value = '  ',
        Enum = '  ',
        Keyword = '  ',
        Snippet = '  ',
        Color = '  ',
        File = '  ',
        Reference = '  ',
        Folder = '  ',
        EnumMember = '  ',
        Constant = '  ',
        Struct = '  ',
        Event = '  ',
        Operator = '  ',
        TypeParameter = '  ',
        Namespace = '  ',
        Package = '  ',
        String = '  ',
        Text = '  ',
        Number = '  ',
        Array = '  ',
        Object = '  ',
        Key = '  ',
        Boolean = '  ',
        Null = '  ',
    },
}
